### ISSUE TITLE
Problems migrating RPG demo to Crafty 0.9

### ISSUE THREAD

**Issue by Pelirrojo** [craftyjs/demos#5]
Hi,

I've been trying to work from RPG demo but I've some problems when I try to update to latest release. There is any migration guide or any documentation?

I've just remove the sentences: ````crafty.canvas.init()```` and move main scene starting to new instructions and to the end of script but there is a problem with reels: **wind** and **walk_left**
`crafty-min.js:12 Uncaught The specified reel walk_left is undefined`

Thanks in advance,
Manuel

**Comment by starwed** [comment]
Sounds like the demo in question is a bit out of date -- to my recollection there haven't been any recent changes to the sprite animation api.

Some docs
- [Intro to animation](http://craftyjs.com/documentation/sprites.html) (but looks like some change to PasteBin embedding has messed with the examples)
- [Full api docs](http://craftyjs.com/api/SpriteAnimation.html)
- [changelog here](https://github.com/craftyjs/Crafty/wiki/Release-Notes), though I don't think there's a migration guide for any changes to the animation structure

I'll take a pass at updating the demos tomorrow -- also looks like the way we use PasteBin needs updating, so some of the documentation examples are missing.  :(

**Comment by Pelirrojo** [comment]
Thank you too much for the links and for a look over the demos. I'm working on a little free promo game rpg-style with random mazes with rot.js & crafty of course :) 

Maybe for code showing and share could be useful:
* jsfiddle or code pen: because are runnable and could be edit 
* gist at github: highlighted code and could be forked, commented, versioned,...

Both could be embedded on webs. 

Thanks, 
Manuel

**Comment by starwed** [comment]
Thanks for the report, I updated the demo and it now works for me locally.  You can see the PR #6 for specific details, but the main culprit was the set of changes introduced in [this pr](https://github.com/craftyjs/Crafty/pull/583#issuecomment-27137206) that made the animation api a bit clearer at the cost of backwards compatibility.  (The switch to time based instead of tick based speeds/durations also required several updates.)

> jsfiddle or code pen: because are runnable and could be edit

I believe we originally used jsfiddle, then moved to jsbin, which now seems to require a pro account for https embedding.  I'll look into ways of fixing that.
